version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  bike-api:
    build:
      context: .
      dockerfile: ./bike-api/Dockerfile
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
        RentContext: "Host=postgres;Port=5432;Database=RentBikeDB;Username=postgres;Password=postgres"
        IdentityContext: "Host=postgres;Port=5432;Database=Identity;Username=postgres;Password=postgres"

  front:
    ports:
        - "5001:3000"
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - bike-api
  
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  


volumes:
  postgres_data:
