version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  bike-api:
    build:
      context: .
      dockerfile: ./bike-api/Dockerfile
    restart: always
    depends_on:
      - postgres
      
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - bike-api
  
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  


volumes:
  postgres_data:
